### ISSUE TITLE
RGI command not found (v4.2.2)

### ISSUE THREAD

**Issue by deepsidhu85** [phac-nml/irida-plugin-amr-detection#10]
When running the amr detection pipeline the analysis fails when trying to run rgi with the error:
`rgi: command not found`

For now to fix this issue you can run the following commands:
conda activate /tool_deps/_conda/envs/__rgi@4.2.2
conda install -c defaults -c conda-forge -c bioconda rgi=4.2.2

**Comment by apetkau** [comment]
Fixed in release `0.2.0` (updates RGI to `5.1.1`) - https://github.com/phac-nml/irida-plugin-amr-detection/releases/tag/0.2.0
